apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaptifi-pv-vol
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/db-data-kaptifi"